server {
   listen ${PORT};

   root /usr/share/nginx/html/;

   error_page 404 /{{ latest }}/404.html;
  
   location /versions.json {
      alias /usr/share/nginx/html/versions.json;
   }
  
   location /latest {
      alias /usr/share/nginx/html/{{ latest }};
   }

   {{#each versions}}
   location /{{ this }} {
      alias /usr/share/nginx/html/{{ this }};
   }
   {{/each}}

   location / {
      return 302 /latest$request_uri;
   }
   
   include /etc/nginx/extra-conf.d/*.conf;
}
