name: Release
on:
  workflow_dispatch:
  release:
    types: [ published ]
  push:
    branches: [ "v[0-9]+.[0-9]+" ]
    paths-ignore:
      - "docs/**"
      - ".github/workflows/release-docs.yml"

env:
  CI: true
  GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_KEY }}
  GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_SECRET }}
  NEXUS_USER: ${{ secrets.NEXUS_USER }}
  NEXUS_TOKEN: ${{ secrets.NEXUS_TOKEN }}
  PATCH: ${{ github.run_number }}
  RELEASE: ${{ github.event_name == 'release' }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: true

      - name: Build
        run: ./gradlew build

      - name: Publish Semver
        run: ./gradlew publishAll

      - name: Publish Snapshots
        run: ./gradlew publishAll
        env:
          SNAPSHOT: true

      - uses: actions/upload-artifact@v7
        with:
          archive: false
          path: build/release.json
          retention-days: 1

      - name: Trigger Test Mod
        uses: peter-evans/repository-dispatch@v4
        if: ${{ github.event_name != 'release' }}
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: ${{ github.actor }}/TestMod
          event-type: trigger-test
          client-payload: '{"version": "${{ github.ref_name }}"}'
