name: Release
on:
  release:
    types: [published]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Update version
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: "gradle.properties"
          property: "plugin_version"
          value: ${{ github.event.release.tag_name }}

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build and upload
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build publishPlugins
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_SECRET }}
