name: Release
on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  CI: true
  GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_KEY }}
  GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_SECRET }}
  NEXUS_USER: ${{ secrets.NEXUS_USER }}
  NEXUS_TOKEN: ${{ secrets.NEXUS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build & Publish
        run: ./gradlew build publishPlugins
        env:
          PATCH: ${{ github.run_number }}