name: Test
on:
  push:
    branches: ["v[0-9]+.[0-9]+"]
    paths-ignore:
      - "docs/**"
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "docs/**"

env:
  CI: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin

      - name: Cache SonarQube packages
        uses: actions/cache@v6
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: ${{ github.event_name != 'push' }}
          dependency-graph: generate-and-submit

      - name: Test
        run: ./gradlew check --stacktrace

      - name: Sonarqube
        if: ${{ github.event_name == 'push' }}
        run: ./gradlew sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-results
          path: "**/reports/tests/test"
          retention-days: 5
